### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by druvus** [mbhall88/tinysink#1]
I would like to package this script using Bioconda. Could you please tag a release that I could use?

**Comment by mbhall88** [comment]
Done https://github.com/mbhall88/tinysink/commit/05adb34a60fac3465f00a46592381f7cf02180e6

**Comment by druvus** [comment]
Thanks!

**Comment by mbhall88** [comment]
You're the one putting it on bioconda - I should be thank *you*.
